# Generated by Django 4.1.7 on 2023-03-03 17:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reasons', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('date_report', models.DateField(default=datetime.datetime(2023, 3, 3, 17, 56, 10, 626228, tzinfo=datetime.timezone.utc))),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.game')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reasons.reason')),
            ],
        ),
    ]
