# Generated by Django 4.1.7 on 2023-02-28 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blacklist.reason'),
        ),
    ]
