# Generated by Django 4.1.7 on 2023-02-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0002_reason_alter_blacklist_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
