# Generated by Django 4.1.7 on 2023-02-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0003_alter_blacklist_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reason',
            old_name='reason',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='blacklist.game'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasons', to='blacklist.reason'),
        ),
    ]
