# Generated by Django 4.1.7 on 2023-03-01 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0004_rename_reason_reason_name_alter_blacklist_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blacklist.reason'),
        ),
    ]
