# Generated by Django 4.1.7 on 2023-03-01 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0005_alter_blacklist_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='date_report',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 3, 12, 19, 648581)),
        ),
    ]
