# Generated by Django 4.1.7 on 2023-03-01 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0011_alter_blacklist_date_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='date_report',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 3, 22, 4, 298472, tzinfo=datetime.timezone.utc)),
        ),
    ]
