# Generated by Django 4.1.7 on 2023-03-01 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0013_alter_blacklist_date_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='date_report',
        ),
    ]
